# Generated by Django 3.1.4 on 2020-12-16 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Floresta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(max_length=100)),
                ('cultura', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('area', models.IntegerField()),
            ],
        ),
    ]
